### ISSUE TITLE
Error With a Large Response Body

### ISSUE THREAD

**Issue by alc0der** [Leopard2A5/fhttp#55]
I am suspecting that this issue happens with extra large response body (41,631 chars).
This is what I am receiving now:
```log
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: TypeError: Cannot read property 'id' of undefined
    at <anonymous>:19:18', fhttp-core/src/response_handler.rs:93:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I am unable to get the backtrace as suggested above. 
The same request works with `curl`

**Comment by Leopard2A5** [comment]
Thanks for the report! Which response handler was used here?

**Comment by alc0der** [comment]
I didn't use a response handling block

**Comment by alc0der** [comment]
I was using Deno, but will try without any response handler and let you know

**Comment by alc0der** [comment]
Never mind the problem was in my script 🤦🏻‍♂️
Sorry for bothering you

**Comment by Leopard2A5** [comment]
No worries :)
