### ISSUE TITLE
Multipart Data with File Upload

### ISSUE THREAD

**Issue by alc0der** [Leopard2A5/fhttp#56]
I believe there is a limitation when it comes to uploading a multipart request that mixes data with other form inputs.
For example something like this `curl` request:

```shell
curl --trace-ascii /dev/stdout -F txtInput=test -F dataFile=@../file.csv --url "http://localhost:8080/files"
```
> Note: I have added `--trace-ascii /dev/stdout` to visualise the request body at byte level

I have tried several ways, but FHTTP doesn't produce valid HTTP request, or doesn't create the request to start with.

**Comment by Leopard2A5** [comment]
You're quite right, file uploads are a weak point and mixing file uploads with other body parts is not supported. The main reason is because I haven't figured out a way to express such a scenario as an *.http file.

I'm open to suggestions!

**Comment by alc0der** [comment]
I like that the *.http files are very similar to raw HTTP, so maybe for starters it should be possible to craft a string based multi part request. Users will still be able to upload flies such as CSV file by typing all values. Binary files support can be added later.

**Comment by Leopard2A5** [comment]
> I like that the *.http files are very similar to raw HTTP, so maybe for starters it should be possible to craft a string based multi part request. Users will still be able to upload flies such as CSV file by typing all values. Binary files support can be added later.

The problem with that - if I understood you correctly - is that since the *.http file is close to the actual thing, empty lines work as part separators. I'll need to investigate whether I can adjust the file format and parser to allow several body parts.

Alternatively I've been thinking about allowing json or yaml request definition files 🤔

**Comment by Leopard2A5** [comment]
Version 1.6.0 adds support for mixed multipart requests. Caveat is that it's only supported in the new JSON and YAML request files (YAML recommended).
