### ISSUE TITLE
Add Support to Output to a File

### ISSUE THREAD

**Issue by alc0der** [Leopard2A5/fhttp#57]
As an IDE (i.e. Fleet) user with limitations on run configs
I want to have an option (-o --output) to channel output to a file
So that I can make a [run configuration](https://www.jetbrains.com/help/fleet/run-configs.html) file simple like this:
```json
{
    "configurations": [
        {
            "type": "command",
            "name": "fhttp",
            "program": "fhttp",
            "args": ["$FILE$", "-o", "log.out"],

        }
}
```

**Comment by Leopard2A5** [comment]
Hi, thanks for the suggestion!
fhttp prints the response bodies to stdout and the log messages to stderr. What would you expect the behavior to be?

**Comment by alc0der** [comment]
I agree that using stdout and stderr is the best. In my cases I am dealing with a json file that allows little room to do any bash piping. Therefore, I was wondering if it is possible to have some output configuration. It is mainly a constraint from the tool (Fleet), which is understandable as it is fairly new.

However, I see a good potential to expand that thought a little bit. Maybe the tool can dump all the responses in the specified location such that they can be referred to later. This can be a great help when debugging a chain of requests. The stdout can remain clean as it is now, but the responses are dumped somewhere in case the user wants to browse them all.

**Comment by Leopard2A5** [comment]
Would you expect both stderr and stdout to be dumped into the file?

**Comment by alc0der** [comment]
I guess it is only stdout

**Comment by Leopard2A5** [comment]
I'll see what I can do!

**Comment by alc0der** [comment]
Thank you!
